# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '01-百思不得姐' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod “pop”
  # Pods for 01-百思不得姐

  target '01-百思不得姐Tests' do
    inherit! :search_paths

pod “pop”
    # Pods for testing
  end

  target '01-百思不得姐UITests' do
    inherit! :search_paths
    # Pods for testing

pod “pop”
  end

end
